### ISSUE TITLE
Support for doc/docx/ppt/pptx formats

### ISSUE THREAD

**Issue by milan-fabian** [milan-fabian/slideshow-support#1]
If you would like to see support for displaying Word and PowerPoint documents in Slideshow, leave +1 here.

**Comment by Selmirrrrr** [comment]
PowerPoint support would definitely be great

**Comment by milan-fabian** [comment]
@Selmirrrrr Adding full PPTX support is quite complicated, currently there is a workaround with uploading the file to Google Drive and setting up File synchronization from Google Drive to Slideshow (https://slideshow.digital/documentation/file-synchronization-google-drive/), the presentation file is automatically converted to a PDF file, which is supported by Slideshow.

**Comment by milan-fabian** [comment]
As there is no up-to-date free library for rendering PowerPoint files on Android, I am closing this issue.

There is an alternative of using Google Drive to convert PowerPoint into PDF.
