### ISSUE TITLE
Support for add borders to panels and reordering layers

### ISSUE THREAD

**Issue by pierloca** [milan-fabian/slideshow-support#11]
Hi, my two pennies for enhancement, could be useful, in case of complex schemas, to have the chance to reorder the layers, and after the great feature for make round corners of the panels would be interesting to add a border feature. Thank you. Great job!

**Comment by milan-fabian** [comment]
Hi, thank you for the suggestion, I have added it to my backlog

**Comment by milan-fabian** [comment]
Borders for panels has been added in release 3.9.2

**Comment by milan-fabian** [comment]
Reordering panels has been enabled in version 3.20.3
