### ISSUE TITLE
Customization and alerts on weather display

### ISSUE THREAD

**Issue by mfs-allison** [milan-fabian/slideshow-support#12]
1. The first day that displays on the weather screen is yesterday. I would like to be able to select what day to start on.
2. It would be nice to customize the text format (in a similar manner to date/time formats) and select my own image sources for the icons.
3. It would also be nice to be able to show severe weather alerts.

**Comment by milan-fabian** [comment]
@mfs-allison 
**1.** Slideshow shouldn't display yesterday's weather (except few minutes after midnight, until weather is refreshed). If you still have yesterdays weather after 1 AM (check the device's time and time zone), please send me Bug report from Slideshow, either from on-screen menu, or web interface, menu Information - Bug report. Bug report will contain logs which will help be diagnose the problem.
**2., 3.** Thank you for suggestions, I will add this to my backlog. Customizing text format shouldn't be very hard, so I could probably add it in the next version, other suggestions are little bit more difficult.

**Comment by milan-fabian** [comment]
Customizing text format for weather forecast has been added in version 3.11.0

**Comment by milan-fabian** [comment]
Customizing weather icons styles has been added in version 3.13.0.
