### ISSUE TITLE
[FR] Show file or exif data as overlay

### ISSUE THREAD

**Issue by M0ebiu5** [milan-fabian/slideshow-support#13]
It would be nice if there would be a possibility to show exif or file meta data as overlay.
eg: creation date of the picture and/or name of the file

More enhanced: show location based on lat/lon in exif data as pinpoint on a map or as text (address)

**Comment by milan-fabian** [comment]
Added in version 3.16.0 - you can set up "Description text" in configuration of an item. This text can contain keywords, such as {DateTime} and {FileName}, which will be replaced with the metadata from the currently displayed file.
