### ISSUE TITLE
[FR] Allow wildcards for directories

### ISSUE THREAD

**Issue by M0ebiu5** [milan-fabian/slideshow-support#14]
Currently slideshow only supports wildcards for filenames - it would be nice, if it would also accept wildcards for directories.

**Comment by milan-fabian** [comment]
Feature was added in version 3.12.0 - you can use wildcards also for directory names, for example `folder*/*.jpg` will pick all files with jpg extension in all folders starting with "folder".

**Comment by M0ebiu5** [comment]
Great! Will try it soon, thanks!
