### ISSUE TITLE
[FR] Allow basic control over touchscreen during slideshow

### ISSUE THREAD

**Issue by M0ebiu5** [milan-fabian/slideshow-support#16]
It should be possible to pause, back and forward the slideshow with touching the screen (left, middle, right for example). The pause function should have a customizable timeout to prevent burn-in.

**Comment by milan-fabian** [comment]
@M0ebiu5 Thank you for all suggestions, I will slowly work on some of them (can't promise any exact date).

Currently it's possible to pause, go forward and backward using keyboard (e.g. connect USB keyboard): https://slideshow.digital/documentation/keyboard-shortcuts/.

**Comment by M0ebiu5** [comment]
My grandmother only has the tablet - without a keyboard :)
Another possibility would be to create an touchable overlay from the webinterface definition - that way, one would only have to set it up once...

**Comment by milan-fabian** [comment]
Basic playback control on the screen has been added in Slideshow 4.0.0. It can be opened by swiping from the right side of screen, or through the left on-screen menu - Media control.
