### ISSUE TITLE
SPECIFIC TIME FRAME FOR SPECIFIC FILE OR FILES

### ISSUE THREAD

**Issue by fnanco2784** [milan-fabian/slideshow-support#17]
I'm not sure if the app does this: I need to set an specific time frame for an specific image o file. For example: Between 06:00am to 08:00am show an specific file. Then from 08am to 11am show an slideshow with several images and videos, and so on....

If it doesn't do this, I can pay for this feature and make it available for all the community.... Also it will be nice to have a tutorial on how to establish a fixed IP to the Android Device and how to access this device remotely so there's is no need to be on the same network of the device to access Slideshow app and change the config.

Best regards,

**Comment by milan-fabian** [comment]
@fnanco2784 
You can use time slots for playlists to set which files should be displayed when. Time slots can be changed via Slideshow's web interface, menu Screen layout - Edit screen layout - Playlist assignment for panel, you can select different playlist for each hour. You can find more information about playlists and time slots on [https://slideshow.digital/documentation/items-playlists-screen-layouts-time-slots/](https://slideshow.digital/documentation/items-playlists-screen-layouts-time-slots/).

Setting fixed / static IP address is different across various Android versions. I might add a generic tutorial in the future, but the best way would be to find tutorial for the particular version you are using.

It is not possible to access Slideshow's web interface remotely without using third-party VPN. I suggest checking synchronization from [Google Drive](https://slideshow.digital/documentation/periodic-download-from-google-drive/) or [Dropbox](https://slideshow.digital/documentation/periodic-download-from-dropbox/) to Slideshow, it can be used as a simplified replacement.
