### ISSUE TITLE
[FR] e-mail mode

### ISSUE THREAD

**Issue by M0ebiu5** [milan-fabian/slideshow-support#18]
Hi Milan, 
thanks for you improvements! I had another idea which i want to share with you - maybe you like it:

Add the ability to read emails, show the attached image(s) and render mail text as overlay.

The slideshow should wait or poll for incoming messages in background on standby or at certain times. In case of a new message, it shows the attachment (if any and possible) and the subject and text as overlay. A timeout (or touch) defines, when the text fades out and only the picture is shown (maybe repeating).
An enhanced version could also navigate back and forth through the mails.

Use case: send elderly people emails with pictures so they can watch them without any further knowledge and action. But there are more situations where this functionality is useful like hotel rooms, message boards, etc

**Comment by milan-fabian** [comment]
Hello,

it's quite an interesting suggestion. However, I currently consider this use case beyond the scope of a digital signage app. So unless there is a commercial request for this feature, or many users ask for it, I will postpone it indefinitely.

**Comment by M0ebiu5** [comment]
Ok, thanks for your answer!

**Comment by stevekompolt** [comment]
You might be able to setup a blog rool and have email to blog setup....?

**Comment by milan-fabian** [comment]
@stevekompolt Could you please specify how would you like this feature to work?

**Comment by M0ebiu5** [comment]
@stevekompolt I'm not familiar with blogs and which would support email posting, but i think it's a pretty good idea...

My solution is a little more extensive: a node-red flow which collects the mails, outputs them as a html page and uploads it to a webserver (oracle always free :)
