### ISSUE TITLE
Network related query

### ISSUE THREAD

**Issue by ravikapoorcci** [milan-fabian/slideshow-support#20]
Dear Team,

First of all a great thanks for software you made so we can use it freely. I just want one more help, is it possible that we can fix ip address of the device anyhow as every time device started it fetch a new address from DHCP. If possible than kindly help me out.

Regards
Ravi Kapoor
Constitution Club of India

**Comment by milan-fabian** [comment]
@ravikapoorcci Hello, I am glad you like Slideshow software :)

It should be possible to set static IP address in the Android settings, but the exact steps depend on the actual Android version. You can try for example this tutorial: [https://www.androidtabletpcsupport.com/2019/10/static-ip-address-on-android-tablets/](https://www.androidtabletpcsupport.com/2019/10/static-ip-address-on-android-tablets/).

P.S. I also replied to your email.

**Comment by ravikapoorcci** [comment]
thanks a lot dear milan
