### ISSUE TITLE
Slideshow screen goes white when another app is used?

### ISSUE THREAD

**Issue by Voss-Active** [milan-fabian/slideshow-support#21]
I want to set the slideshow up running on one screen, whilst then using another screen for other apps.  This worked fine, but mostly, when you go to another app, the slideshow player just goes white.  When you click on the slideshow screen again it continues.

Running in a 2021 i5 Aser Chromebox
Permission to run over other apps i set

Is there a sulution for this?

**Comment by milan-fabian** [comment]
@Voss-Active Thank you for your suggestion. Slideshow currently doesn't have proper support for multi-window mode, as Android lowers the priority of the app when you go to another app.

I will try to make some changes in Slideshow, that would enable use in multi-window mode, but it will take some time. If you are willing to help us with testing, I can then send you a beta version.

**Comment by Voss-Active** [comment]
I see.  Thanks.  It did work for a while, but then went white.

I could try a beta sure :-)

Mvh / Kind Regards

*ALLAN ELLARD* | Operation Manager
+47 56 51 05 25

*VOSS ACTIVE AS* | www.vossactive.no
*Partner Norway* Active AS

<http://www.vossactive.no/>
