### ISSUE TITLE
how to use mqtt

### ISSUE THREAD

**Issue by pierloca** [milan-fabian/slideshow-support#22]
hi, could you please realize the documentation about mqtt, or explain it here, i'd like to use it for a new project, i have a mosquitto server but i don't know how to use topics/messages inside slideshow, i found no element i can use to show or manage them ( on 3.17 version). thanks a lot!

**Comment by milan-fabian** [comment]
@pierloca Hello, MQTT support is highly experimental in version 3.17.0, a little bit better support will be added in the upcoming version, hopefully released within a week. I will share basic examples with you afterwards.

The idea behind MQTT integration in Slideshow is that the app will connect to an MQTT server and listen for basic commands, for example move to the next file, return device info, change the current playlist. You can use it to issue commands to Slideshow instances across the internet, without need for direct access.

**Comment by pierloca** [comment]
Hi, great, it was my goal, i'll wait, thanks a lot! I'm really curious
about It

Il mer 12 mag 2021, 22:20 Milan Fabian ***@***.***> ha
scritto:

**Comment by milan-fabian** [comment]
@pierloca You can find documentation for MQTT integration in Slideshow on https://slideshow.digital/documentation/mqtt-integration/
It is valid for Slideshow version 3.17.3, which has been published today: https://slideshow.digital/version-history/

**Comment by pierloca** [comment]
very good, it works like a charm, if possible, for future upgrades could be useful to avoid the mac number in the request string to allow to use mqtt one to more, and move the capacity to work one to one to the topic prefix if needed.

**Comment by milan-fabian** [comment]
We are currently aiming at separate topic for each device, so they could be managed separately. Sending message to multiple devices can be implemented as sending the same message to multiple MQTT topics.
