### ISSUE TITLE
html files do not show

### ISSUE THREAD

**Issue by pierloca** [milan-fabian/slideshow-support#23]
Hi, I have some machines with slideshow on: android box, android tv, tablet, with different versions of android from 7 to 10. 
Some of them can't show html files, the strange thing is that if i send an html file or use the internal html editor, on the screen nothing appears, but if i use the internal screenshot tool to take a screenshot, it shows the html panel, and the page in the right way. 
More strangely, normally my panels have rounded corners, so they have 4 "transparent  triangles" on the corners, in the  machines that do not show the panel, the panels are transparent and the triangles are shown, the perfect opposite image.
It does not seem to be a problem with the android version because same version on different machine gives different results.
have you face this behaviour?

**Comment by milan-fabian** [comment]
@pierloca Hi, we got you email about this issue and replied last Wednesday, maybe the reply got stuck in spam folder?

Just to be sure, I am copying the answer below:

> Slideshow uses an internal Android browser (sometimes visible as a "WebView" app in the list of apps) for displaying HTML files. It's not the same as the default browser, so I suggest checking if there is possibility to update the WebView app on the "malfunctional" devices (usually isn't, though).
> 
> Depending on the hardware, sometimes turning off "Enable enhanced video player" helps with the rendering issues, you can find it in the web interface, menu Settings - Device settings. It switches Slideshow to a different rendering mode, which has worse video playback compatibility, but sometimes helps with the rounded corners (not always).
> 
> If that doesn't help, could you please share a bug report with us when Slideshow displays the hidden triangles in the corners? You can send one via the web interface - menu Information - Bug report, it will contain a copy of the configuration you set up, so I can upload it to my test device and try to fix it.

**Comment by pierloca** [comment]
@milan-fabian, thanks, you gave me a good advice, it's a problem with rounded corners, i have yet disabled enhanced player but they continue not to show, instead, i didn't think about, without (or 1px) rounded corners, the panel shows the html page. now the strange thing is why on certain rom it happens and in other not, but it resolve in part my problem.

**Comment by milan-fabian** [comment]
@pierloca Rendering rounded corners uses hardware acceleration and unfortunately, various devices might implement it differently. I would still appreciate a bug report from Slideshow from a device where the rounded corners are not displayed correctly, so I can analyze if there is something that can be changed from our side.

**Comment by milan-fabian** [comment]
@pierloca Thank you for the bug report, I loaded the configuration into my test device and the rounded corners are displayed correctly even with HTML. So there is probably something specific with some of your devices.

By the way, your screen layout is really well done, it looks very nice. I can see that you prepared several layouts which are almost the same, only rotated. You can achieve a similar result by enabling "Rotate layout every day" in the Device settings.
