### ISSUE TITLE
Some of my slides are being cut off

### ISSUE THREAD

**Issue by mcsmikgh** [milan-fabian/slideshow-support#24]
Hi there,
I recently discovered this app and installed it in my amazon fire tv. 
It's amazing, but there is one thing I can't yet get to figure out - 
I have videos with different duration and some of them end up being cut off before the end -  how can I adjust the app to allow each video to playback until its actual end?
Thanks very much in advance and best regards,
Michael.

**Comment by milan-fabian** [comment]
Hello, 

Can you please check setting "Video timeout" via Slideshow's web interface - menu Settings - Device settings? It should be set longer than your longest video.

If the setting is correct and the videos are still cut off, could you please send me a bug report from Slideshow app right after it happens, via web interface - menu Information - Bug report? It will contain logs from the device which should help me diagnose the problem.

**Comment by mcsmikgh** [comment]
Hi Fabian,

Thanks so much for your reply!
I just updated the settings to my longest video, which is 21secs, but the
videos continue to get cut off at different time points.
Also I just sent a bug report as you indicated.
Thank you so much in advance and I look forward to hearing from you.
Best regards!

Michael.

**Comment by milan-fabian** [comment]
Thank you for sending the bug report, I can see that there is a problem with hardware decoding of the video few seconds before then end, right around the time Slideshow start pre-loading the next video.

Can you please try disabling option "Enable enhanced video player" in the Device settings and restarting Slideshow app? It will disable also pre-loading the videos in advance, which might help on your hardware.

**Comment by mcsmikgh** [comment]
Hi Fabian,
Thanks for looking into this.
I disabled the option "Enable enhanced video player" as per your suggestion and as a result all videos played back entirely and without getting cut off. although this created another issue - these videos are formatted at 1080x1920 (vertical) to display on a vertical screen.
After I disabled the option "Enable enhanced video player"  the image on the screen was stretched to adapt to horizontal formatting.
I tried tweaking the screen orientation settings in the "Slideshow" app, but this didn't produce any good results, because the tv has been setup to show images vertically.
I am not sure if this makes sense, I hope I explained it correctly.
Is there any other way that I could get the videos to show entirely without getting clipped off?

Thanks and best regards,
Michael.

**Comment by milan-fabian** [comment]
The side effect of disabling enhanced video player is also disabling rotation on the screen (non-enhanced video player doesn't support rotation). I will separate these two options in the next version of Slideshow (released hopefully within a week).

Until then, the only solutions I can currently think of are re-encoding the video and rotating it using some video editing software, or trying different hardware, capable of pre-loading the video.

**Comment by mcsmikgh** [comment]
Wow, thanks Fabian, this is a great idea. I will re-encode and rotate the video meanwhile and I will look forward to the upcoming release of Slideshow.
How can I find out when the release is out?
Thanks so much for all your help!
Michael.

**Comment by milan-fabian** [comment]
I will notify you here once the new version is released.

**Comment by mcsmikgh** [comment]
Thank you so much!

**Comment by milan-fabian** [comment]
New version 3.17.12 (https://slideshow.digital/version-history/) has a setting for disabling the preloading "Preload items in playlist".

I suggest the following combination for you:
```
Enable enhanced video player - Enable
Preload items in playlist - Disable
```

**Comment by mcsmikgh** [comment]
Hi Fabian,
Thanks for letting me know!
I downloaded the "universal apk" file, and ran the update from the remote management screen on my computer. (screenshot attached)
However the app did not reload on the tv and the app version seems to remain unchanged, so I could see that the update did not take place.
I also tried to update using the ftp option but no luck.

What is the best way to run the update?

Thanks in advance and best regards!
Michael.
![Screenshot 8-9-2021 9-41-14 AM](https://user-images.githubusercontent.com/88339085/128708160-eb1618bb-0b18-43aa-850d-9daf484f02a3.png)

**Comment by milan-fabian** [comment]
Hello,

as noted on the screenshot, your Android device is not rooted, so it doesn't support update via Slideshow's web interface (https://slideshow.digital/documentation/root-on-android/).

You can update Slideshow for example by downloading the APK file directly into your Android device and launching the installation by opening the APK file in any file browser app on your Android device.

**Comment by mcsmikgh** [comment]
Hi Fabian,
Thanks for your reply.
I uninstalled the app, then reinstalled it and it works perfectly now, the fixes you included in the newest version took care of the issues that I was having.
Thanks so much for taking the time to help me fix this problem. :)
Best regards,
Michael.
