### ISSUE TITLE
Videos being cut a few seconds before their ending

### ISSUE THREAD

**Issue by EstagiarioSanco** [milan-fabian/slideshow-support#27]
Good afternoon, I'm contacting you to report a bug I've been experiencing with your application. 
When I'm showcasing videos, they cut a few seconds before the ending, which leads to some video content to not be shown. 
Appreciate the attention.

**Comment by milan-fabian** [comment]
Hello,

The probable reason is the feature "Preload items in playlist", which starts preloading (caching) the next video few seconds before the previous video is finished. The video hardware decoder on some devices has problems with handling multiple videos at the same time and the result is similar to what you are observing.

I suggest disabling this feature for now, via Slideshow's web interface - menu Settings - Device settings - uncheck "Preload items in playlist" and restart Slideshow app.

**Comment by EstagiarioSanco** [comment]
Aprecciate the quick response, everything is working correctly now.
