### ISSUE TITLE
Support for Grafana

### ISSUE THREAD

**Issue by bubblefish432** [milan-fabian/slideshow-support#28]
Hallo,

It is possible to show Grafana Screens http://play.grafana.org ?

**Comment by milan-fabian** [comment]
@bubblefish432 Hello, it is possible to show web pages in general, you can use the tutorial on https://slideshow.digital/2020/09/how-to-display-web-page-on-the-screen/, just replace the URL.

Whether Grafana Screens displays correctly depends highly on the version of the internal WebView component of your Android device. For example, on my test device with Android 7 I got an error message that the browser is unsupported by Grafana. On another test device with Android 12 it displayed without any problem.
