### ISSUE TITLE
Enable AndroidTV Remote Enter/Circle Button Support to Invoke Menu

### ISSUE THREAD

**Issue by Tribalwarfare** [milan-fabian/slideshow-support#31]
Hi Can we please have AndroidTV remote Enter Button/Accept button support to invoke the OnScreen Menu?
Or can we have a bind setting on the web server to bind the key?

Sometimes a remote site will need to open the app manually and start the playlist but we cannot invoke the menu using an Android TV compatible remote.

Kind Regards,
AG

**Comment by milan-fabian** [comment]
Hello, currently it should be possible to use the "menu button" on the remote control to open the on-screen menu, if your remote control has such button.

Custom key mapping is planned for Slideshow 4.0.0, which should be released in November. In this version it will be possible to map to Enter button to opening the on-screen menu.

**Comment by Tribalwarfare** [comment]
> Hello, currently it should be possible to use the "menu button" on the remote control to open the on-screen menu, if your remote control has such button.
> 
> Custom key mapping is planned for Slideshow 4.0.0, which should be released in November. In this version it will be possible to map to Enter button to opening the on-screen menu.

Wow thank you. That will be a great enhancement as I have come to realize some vendors implementations for AndroidTV hardware can be problematic at times. Thank you for taking the time to respond to my request.

Kind Regards,
AG

**Comment by milan-fabian** [comment]
Custom key mapping was added in Slideshow 4.0.0, it is accessible though menu Settings - Key mapping

https://slideshow.digital/documentation/keyboard-shortcuts/
