### ISSUE TITLE
Advanced settings inside app not working (ERR_TOO_MANY_RETRIES)

### ISSUE THREAD

**Issue by AdmiralStipe** [milan-fabian/slideshow-support#32]
When trying to access Advanced settings inside the app on the device, I get blank screen with an  error message
"Website not available, http://127.0.0.1:8080/ could not be opened because of: 
net. ERR_TOO_MANY_RETRIES"

If I try to open the link in a web browser on the same device (127.0.0.1:8080 or localhost:8080) it works OK, just not inside the app itself. Log and Logcat show nothing unusual, when this happens. 

It happens on my phone (Redmi Note 11 Pro+), but I can't try it on actual devices, where the app is also installed (two smart TV's), as they are in use for other purpose at the moment for next couple of days.

**Comment by milan-fabian** [comment]
@AdmiralStipe Did you leave the default username / password (admin / admin), or did you change the password?

Changing password might be a cause of this error, as the advanced settings are not accessible directly with changed password.

**Comment by AdmiralStipe** [comment]
You are right, I changed the password as our safety policy forbids using default passwords.
Is there a workaround to this issue? I mean, most of the time I'm using web interface from my PC anyway, but sometimes it's still necessary to access the Advanced settings directly from the device...

**Comment by milan-fabian** [comment]
Currently advanced settings are locked only for credentials admin/admin.

Would it be OK if I add a dialog for entering username/password after opening the advanced settings, if the default credentials have been changed?

**Comment by AdmiralStipe** [comment]
For me it would be totally OK. I guess it's also added value, as this way really noone can localy access (unattended device) critical settings and content without the password.
