### ISSUE TITLE
Feature request: Last synchronized timestamp

### ISSUE THREAD

**Issue by kentare** [milan-fabian/slideshow-support#35]
Really an extension of this: #33 

**Request**: When getting device info (I use mqtt for remote pseudo-control over slideshow) it would be great if I could get synchronization information with a timestamp and if the synch was manual or automatic.  

Maybe something like this?
```
{
...device info,
lastSynchronized: manual-1675496322
}
```
```
{
...device info,
lastSynchronized: auto-1675496322
}
```
```
{
...device info,
lastSynchronized: null
}
```

**Comment by milan-fabian** [comment]
@kentare The device info response is getting quite large, I would rather make a new endpoint (`synchronize/status`?) for getting info about the last file synchronization with more details, like this:
```
{
   "lastSynchronization": {
      "timestamp": "2023-02-04T10:44:00+01:00",
      "triggered": "manual",
      "filesDownloaded": 3,
      "filesFailed": 0
   }
}
```

I will have a look at it in the next version.

**Comment by kentare** [comment]
I think that is a good solution @milan-fabian

**Comment by milan-fabian** [comment]
@kentare there is a new version of Slideshow app available on https://slideshow.digital/apk/4.3.0/slideshow-android-4.3.0.apk, with added support for checking the synchronization status (among other new features). It is available through endpoint `synchronize/last`, either via MQTT operation `synchronize/last` or HTTP REST API `GET /ajax/synchronize/last`.

This version is not published yet, I will do it in a few days after finishing up all the testing. If you have some free time, I would appreciate it if you could test this new version as well.

**Comment by kentare** [comment]
@milan-fabian I will try to test the new version this weekend

**Comment by milan-fabian** [comment]
@kentare I suggest writing an email to slideshow@slideshow.digital, it's the fastest way.
