### ISSUE TITLE
Feature Request: support for webpages with username and password

### ISSUE THREAD

**Issue by ulfskogeng** [milan-fabian/slideshow-support#36]
The title says it all. I have a webpage that I would like to display, but it's with username and password. Is it possible to make a solution of some kind with support to display URL with authentication?

**Comment by milan-fabian** [comment]
Slideshow already supports web authentication at some level:

- For HTTP basic authentication, enter then URL in the following format: `https://username:password@webpage.domain`, for example `https://user:pass123@example.com`
- For cookies authentication (using login form), you can use "Enter web page" option in File Manager, then click on Scan page and fill the details. As there are many various methods for login form, this method might not work on all pages.
![image](https://user-images.githubusercontent.com/6372867/218533367-544d85ce-bb70-46ed-92c0-fd7a263b8da5.png)

**Comment by ulfskogeng** [comment]
@milan-fabian thx for you feedback/suggestions. None of the methods will work for the webpage that I'm trying to display. I'm waiting for the developer to make a public page that will not require any authentication. Hope it will come soon!

**Comment by milan-fabian** [comment]
@ulfskogeng If the current login page is accessible from the internet, can you please share the URL? If you don't want to publish it here, you can send it to milan@slideshow.digital.
I will have a look at the login page and check whether there is any possibility for Slideshow to log in.

**Comment by milan-fabian** [comment]
The problem was solved by URL encoding the special characters in the URL. 

Documentation on https://slideshow.digital/documentation/web-pages/ was updated to reflect this.
