### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by MarleTangible** [milan-fabian/slideshow-support#39]
Is there a way to control the screen resolution?
I would like to use some websites that requires the digital signage to have resolution of 1920x1080. Thank you in advance.

**Comment by milan-fabian** [comment]
@MarleTangible Slideshow app uses the same resolution as Android system, it can't change it. You can check the settings of your Android device whether it supports changing resolution, but there is a high chance the resolution is fixed.
In case of websites it might help to change setting "Web page zoom" via Slideshow's web interface - menu Settings - Device settings.

**Comment by MarleTangible** [comment]
Milan, thank you for the information. I'll look into the settings and see
what the device supports. Have a great day.

Ihsan Topaloglu
Systems Architect
*Marle Tangible*
