### ISSUE TITLE
Feature Request: NDI Video support

### ISSUE THREAD

**Issue by mengbers** [milan-fabian/slideshow-support#41]
I would love to connect our Slideshow in our church foyer to the livestream we send out from our sanctuary. The standard format used by OSB  for output on an internal network is NDI.  I think that would be a valuable support.

**Comment by milan-fabian** [comment]
To be honest, NDI is not a very widely used format in the digital signage world, so unless there is a commercial request, we are currently not considering adding support for NDI into Slideshow. We are currently supporting mainly standard HTTP and RTSP streams.

Out of curiosity, do you mean OSB or OBS?

**Comment by mengbers** [comment]
Yes - OBS.  Thanks for the response.

**Comment by milan-fabian** [comment]
I suggest using this plugin with OBS: https://obsproject.com/forum/resources/obs-rtspserver.1037/
Slideshow can display RTSP stream, so it should work together.
