### ISSUE TITLE
Smart Tv android and Tablet Samsung 7 -inche  the periodic remote loading 

### ISSUE THREAD

**Issue by Renderman2020** [milan-fabian/slideshow-support#42]
Is there any way that the slideshow application can run on smart TV the periodic remote loading and also on a 7-inch Samsung tablet from Amazon greetings

**Comment by milan-fabian** [comment]
Slideshow can be installed on almost any Android device with Android 5.0 or newer, so if you have Android TV and Android tablet, it should work. 

You can find out more on https://slideshow.digital/how-to-get-it/ and https://slideshow.digital/documentation/file-synchronization-http-ftp/.
