### ISSUE TITLE
No USB storage found

### ISSUE THREAD

**Issue by betoled** [milan-fabian/slideshow-support#45]
Hi,

When connecting an USB flash drive a message pops up with the message "No USB storage found".
The files are no copies to the player, and nothing else happens.

The logs states

> USB media inserted: path:///mnt/media_rw/1C42-C554 based on action=null, previously mounted=false
> 2023-06-28 10:53:20 WARN sk.mimac.slideshow.MountListener - No USB flash drive found

Am I doing something wrong ?

Benjamien

**Comment by milan-fabian** [comment]
Hello @betoled 

The most common issue is that folder "slideshow" doesn't exist on the USB flash drive. The folder name can be changed via setting "Folder on Flash drive", the default value is "slideshow".
