### ISSUE TITLE
Question/request: Include looping video for a specified amount of time on a playlist

### ISSUE THREAD

**Issue by lukestein** [milan-fabian/slideshow-support#47]
Hi. I am wondering if it is (or could be) possible to include a piece of video content in a playlist and have it loop for a fixed amount of time rather than play only once. This from the documentation suggests it isn't currently possible (and I can't find it in the UI):

> During the cycle, each content is resolved to only a single file, image or stream. This is then played for a set amount of seconds (except for audio files, video files and moving RSS messages, which are always played for their full length)

**Comment by milan-fabian** [comment]
@lukestein It is not possible to directly set the amount of time or looping, but I would suggest a workaround:

1. Create separate Content for the video and for the other media (e.g. upload it to different folders in File manager, then right-click the folder - Create new content)
2. Create a new Playlist through menu Playlists
3. Add the Video Content to this Playlist multiple times, one time after another (e.g. 5 lines if you would like to play the video five times)
4. Add the Other media content to this Playlist, at the end

**Comment by lukestein** [comment]
Thank you. This is where I'd wound up, too.
