### ISSUE TITLE
camera on my surface pro 4 

### ISSUE THREAD

**Issue by djsame** [milan-fabian/slideshow-support#49]
Hello, 
I'm a "slideshow" user.
I use "surface pro 4 (windows 10)" to send photos to the "slideshow" on my android tablet via my browser.
Is it possible to use the camera on my surface pro 4 to send a photo directly to slideshow?  
Thank you.
Stephane

**Comment by milan-fabian** [comment]
@djsame Hello, Slideshow's web interface allows image upload, but it doesn't have access to the device's camera.
So the only way would be taking the picture in advance and then uploading the picture to Slideshow.

**Comment by djsame** [comment]
Hello, thank you for this information, and also for your speed.
Have a nice day!
