### ISSUE TITLE
Delete playlists

### ISSUE THREAD

**Issue by jaredb79** [milan-fabian/slideshow-support#50]
Love the app, just tried to send you an email, but it kept failing.

Anyway, would be great to have a way to delete playlist. I tried to delete some content, but it said it was in a playlist even though it's not. I have playlist I want to get rid of too. Just want to clean up basically.

Cheers

**Comment by milan-fabian** [comment]
@jaredb79 On the Edit content page, you should have either something in "Used in playlists" section, or the Delete button should be enabled.
If there is something in "Used in playlist" section, please click on the particular playlist and then check "Used in zones" section on the following page.
