### ISSUE TITLE
File Sync not working

### ISSUE THREAD

**Issue by rudwij** [milan-fabian/slideshow-support#51]
Hi,  2 days ago I found that the File Sync via Google Drive is not working.. so I login into the app and go straight to File Sync Menu and it show as below 
![image](https://github.com/milan-fabian/slideshow-support/assets/163837617/25454fe3-1941-4b90-ab71-787aba3cbabc)

Would you please look into it ??

**Comment by milan-fabian** [comment]
As replied by email, these steps should fix the problem:

- Open Slideshow's web interface - menu Settings - Shell console
- Enter the following command and press Send: `rm -rf /data/data/sk.mimac.slideshow/app_data/tokens`
- Reload Slideshow app
- Open the File synchronization page again, you might need to re-login to Google Drive account
