### ISSUE TITLE
screen save & display MQTT JSON

### ISSUE THREAD

**Issue by frgithub35** [milan-fabian/slideshow-support#52]
Hi Milan,
great job on this app! 
I was looking for a simple, high-performance digital signage system for the home and I think I've found what I need.
2 suggestions or features I haven't discovered yet:
1/ be able to make a real screen saver, not a black screen with 'Touch me' scrolling through it
2/ display JSON data received via MQTT
for example, IOT data such as temperature, ...

regards

**Comment by milan-fabian** [comment]
Hello,

1. Could you please explain what you mean by real screen saver? 
2. I have a feeling that just displaying raw JSON data wouldn't be enough, as usually some kind of processing is needed, such as extracting the value from JSON, formatting it etc. Would it be better to process the data on a 3rd party software, such as Home Assistant and use Slideshow just for displaying the dashboard?

**Comment by jssystemcz** [comment]
Hello everyone :-)
I just wanted to contribute my solution.
I process the data in NODE-RED and then display it as a web page that I have customized for display.
It looks something like this...
![20240308_192421](https://github.com/milan-fabian/slideshow-support/assets/55037201/f107d922-b206-462d-9178-6f6aeb686db1)

Zdravím Milane, a díky za tvou skělou práci!
