### ISSUE TITLE
Feature Request: Locking the app with triple tap in touch screen kiosk environments

### ISSUE THREAD

**Issue by altonmazin** [milan-fabian/slideshow-support#54]
It would be great if there is a way to lock the app from being able to get to the swipe left and right menus by implementing a lock mode such as tapping a corner few times.

when using this application in a kiosk environment  with touch screen, users are easily able to exit the app by swiping to get to the side panel menu. which then allows them to either modify settings or attempt to exit the app.

implement tap to unlock feature to lock the screen from being able to display the right, left or both menus
implement unlock passcode to ensure only admin is able to unlock if attempt is made to exit the application from the triple tap or something similar.

**Comment by milan-fabian** [comment]
Hello @altonmazin,

We are aware that the end user can easily quit Slideshow by opening the on-screen menu and we are offering locking the menu as a part of our Branding package https://slideshow.digital/branding/.

We have considered adding locking to the publicly available version of Slideshow, however that would allow completely locking on some Android devices (e.g. combination of Start on boot + locked on screen menu + forgotten password) and that would be quite a bad situation for less technical users. So right now, allowing this feature publicly is not worth the amount of new support requests. I hope you understand.

**Comment by altonmazin** [comment]
okay i see, when we use kiosk applications we normally do triple taps or
some sort of exit hidden area on the screen which then unlocks to ensure
people are not completely locked out. but understand that's your design on
the app.

If we need this feature, how long would it take to get us a lockable apk?
after payment is made?

**Comment by milan-fabian** [comment]
Preparation of the branded app with on-screen menu lock takes about 3-4 days

**Comment by altonmazin** [comment]
Hi Milan,

let's please prepare this custom version and provide a link to pay.
hopefully still can deliver within few days.

assuming the left side menu will have an option to turn on/off?
also, what about the right side menu? that would be great if that one can
be disabled as well.

thanks,

**Comment by milan-fabian** [comment]
Hello, please contact us on slideshow@slideshow.digital for more details. 
GitHub issues are public and we prefer to keep it for support and actual issues only.
