### ISSUE TITLE
problem with connecting to the http://[ip address]:8080

### ISSUE THREAD

**Issue by elemeledutki** [milan-fabian/slideshow-support#55]
Its not an issue I guess, but I can not solve that:
I have an old android tv (running A5.1.1), with slideshow installed and working. I have a regular PC running Windows 10. I can not connect from PC to the http://192.168.1.132:8080 (the IP address is correct) - ERR_CONNECTION_TIMED_OUT.
I tried to change the "HTTP port" from "80" (dafault) to "8080", but with no luck neither.

I have AnyDesk installed on tv as well - and I can connect with no problems.

When I ping 192.168.1.132:
![image](https://github.com/milan-fabian/slideshow-support/assets/65021004/66763a8a-f4fe-4b56-b05c-1d987d4d5dd0)

Any ideas?

**Comment by milan-fabian** [comment]
@elemeledutki "Destination host unreachable" during ping means that there is some kind of routing problem on the network, or the device is not connected at all. So it is a network problem, your computer can't reach the Android TV at all, on any port (not just 8080 for Slideshow).

**Comment by elemeledutki** [comment]
Its true, indeed. But - as I mentioned - I can connect with android machine the same time when I can not with slideshow.

ANYHOW - I solved the problem. The tv is wirelessly donnected to the open network (I just didnt remember the password to the protected one). Google - on that condition (unsecure network) creates its own VPN - which takes the traffic. Thats why I had routing problems - after switching to secured network - all problems are gone:)

**Comment by elemeledutki** [comment]
Closed - in case someone puts that on the machine on open network.
