### ISSUE TITLE
Webserver not properly loading

### ISSUE THREAD

**Issue by alvaroamarz** [milan-fabian/slideshow-support#56]
Dear Support. I´m trying to use Slideshow on a Giada DN73 player, running Android 10. Installation goes straightforward, but when I try to access admin webpage from my pc (Windows 10, running Chrome or Edge), it takes ages to parcially load the page. With that interface, is impossible to interact. I´m not sure if there is something to do on Android or on my browser. I´ve tried to connect to the player with different devices and result is always the same. 
On the other hand, I did the test of installing Slideshow on my Samsung Galaxy S24Ultra and it worked perfectly, entering to the webpage from the same computer.
I will really appreciate any help that you could give me.
Kind Regards, Alvaro

![image](https://github.com/user-attachments/assets/656a2484-81b5-4c7f-af1f-15507d4b61f8)

**Comment by milan-fabian** [comment]
Hello @alvaroamarz,

Please make sure the internet connection between the Android player and your computer is stable and fast. We have seen similar problems when the WiFi on the Android player was laggy and too slow.
Slideshow's web interface is really lightweight, it doesn't transfer large amount of data.

**Comment by alvaroamarz** [comment]
Dear Milan. Thanks for your reply.

Connection between player and computer is over wired LAN.

Over the same LAN, but even using WiFi, I installed the app on my phone and
it worked.

Any suggestions or troubleshooting?

Kind Regards, Alvaro

**Comment by milan-fabian** [comment]
I highly suggest checking if the networking, storage speed and performance of your device is reasonably good. You can use third party benchmarks for this.

**Comment by alvaroamarz** [comment]
Milan, don´t you have anyway of checking if some things are being blocked
or some port or something? Maybe over adb or shell?

Thanks in advance!

Kind Regards, Alvaro


Alvaro Amar Zajer
Gerente General
Lapshop Servicios y Tecnología SpA
+56 9 83607377
San Pío X 2445, Oficina 803
Providencia, Santiago, Chile
www.lapshop.cl
***@***.***

**Comment by milan-fabian** [comment]
Hello, is this issue still persistent?

**Comment by alvaroamarz** [comment]
Hi, using ethernet connection was not possible to use the webserver. Using
wifi, was possible.

Is there any way to tell the software what interface to use?

Regards, Alvaro

**Comment by milan-fabian** [comment]
Slideshow is accessible on all network interfaces that Android OS is connected to.

**Comment by alvaroamarz** [comment]
In my case, it wasnt.

Connected over Ethernet, you could reach the webpage, otherwise it was
eternally trying to load it completely. With WiFi,, behavior was totally
different. In 1 or 2 seconds, the page was loaded completely.

Regards, Alvaro
