### ISSUE TITLE
can't connect to MSTT server mosquitto

### ISSUE THREAD

**Issue by frgithub35** [milan-fabian/slideshow-support#57]
Hi, 

I've just installed a new MQTT mosquitto broker version 1.5.7 (https://mosquitto.org/man/mosquitto-8.html)
It supports MQTT protocol version 5.0/3.1.1/3.1
I have no problem with other application like MQTTExplorer or arduino IOT

I can't connect to it with or without user/password
with or without TLS
with or without Websocket

the logs are : 
2024-07-24 10:49:29 INFO sk.mimac.slideshow.mqtt.MqttService - Connecting to MQTT server '192.168.1.10' and topics 'SLIDESHOW/REQ/AndroidTV/+'
2024-07-24 10:49:30 WARN sk.mimac.slideshow.mqtt.MqttService - Error in MQTT connection
com.hivemq.client.mqtt.mqtt5.exceptions.Mqtt5ConnAckException: CONNECT failed as CONNACK contained an Error Code: UNSUPPORTED_PROTOCOL_VERSION.

**Comment by milan-fabian** [comment]
Hello @frgithub35,

Mosquitto 1.5.7 doesn't support MQTT 5.0, as the support was added in Mosquitto 1.6 (https://mosquitto.org/blog/2019/04/version-1-6-released/).
I highly suggest upgrading to Mosquitto 2.x, we are using Slideshow with Mosquitto 2.0.11 on multiple projects without any issues.

**Comment by frgithub35** [comment]
Hi, 
I thought I was up to date with my version of mosquitto, but it was installed on an old Debian.
I updated all that and everything's back in order
Thanks again for this
