### ISSUE TITLE
File synchronization for Google drive not working

### ISSUE THREAD

**Issue by carlmaxx97** [milan-fabian/slideshow-support#58]
After selecting google account, it shown

This app is blocked

This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

This cause google login process interrupt.

**Comment by milan-fabian** [comment]
Unfortunately, Google changed their API conditions (again...) and they now require a full paid audit if we want to continue having full access to Google Drive for more than 100 user accounts. We are working on finding the best way to get an audit, while checking other possibilities for integration with Google as an alternative.

I hope we will have a realistic time frame for solving this issue soon. In the meantime, we updated https://slideshow.digital/documentation/file-synchronization-google-drive/ to reflect the current status.

**Comment by garyzimmer** [comment]
Did something change with this? It looks to be working again.

**Comment by milan-fabian** [comment]
Yes, we passed the audit and Google approved the results today, so the login to Google Drive should start gradually working. We are still checking if everything is OK, we would appreciate feedback if you find anything suspicious.

**Comment by garyzimmer** [comment]
Looks all good on my end! I had a device that was logged in previously, just start resyncing on it's own.
Also, I just signed in on a new device with no problems!
