### ISSUE TITLE
remote install new configuration

### ISSUE THREAD

**Issue by pierloca** [milan-fabian/slideshow-support#6]
Could be usefull to have the chance to download and install new configuration from a ftp o google drive.
could be possible?

**Comment by milan-fabian** [comment]
I think it could be possible, but it would be necessary to be very careful when preparing the new configuration for remote upload (wrong configuration can break the app).
I will try to implement it in the following weeks.

Thank you for the suggestion.

**Comment by pierloca** [comment]
great, i agree to be carefull, anyway, really a good job!
thanks
pier luca

Il giorno ven 3 apr 2020 alle ore 17:53 Milan Fabian <
notifications@github.com> ha scritto:

**Comment by milan-fabian** [comment]
I added this functionality in version 3.6.1, see update of documentation how to set it up:
https://slideshow.digital/documentation/setup-csv-file/
